name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Typst
      uses: lvignoli/typst-action@main
      with:
        source_file: main.typ
    - name: Upload PDF file
      uses: actions/upload-artifact@v4
      with:
        name: dmitritsiu_resume
        path: "*.pdf"
    - name: Get current date
      id: date
      run: echo "DATE=$(date +%Y-%m-%d-%H:%M)" >> $GITHUB_ENV
    - name: Release
      uses: softprops/action-gh-release@v1
      if: github.ref_type == 'tag'
      with:
        name: "${{ github.ref_name }} — ${{ env.DATE }}"
        files: main.pdf
